# Generated by Django 5.2.9 on 2025-12-19 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('worldview', models.TextField()),
                ('location', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('current_location', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='llm.rooms')),
            ],
            options={
                'db_table': 'characters',
            },
        ),
        migrations.CreateModel(
            name='ShortTermMemories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='llm.rooms')),
            ],
            options={
                'db_table': 'short_term_memories',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['username'], name='users_usernam_baeb4b_idx')],
            },
        ),
        migrations.AddField(
            model_name='rooms',
            name='creator_id',
            field=models.ForeignKey(db_column='creator_id', on_delete=django.db.models.deletion.CASCADE, to='llm.users'),
        ),
        migrations.CreateModel(
            name='LongTermMemories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('embedding', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='llm.rooms')),
            ],
            options={
                'db_table': 'long_term_memories',
                'indexes': [models.Index(fields=['room_id'], name='long_term_m_room_id_e2a720_idx')],
            },
        ),
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('current_location', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character_id', models.ForeignKey(db_column='character_id', on_delete=django.db.models.deletion.CASCADE, to='llm.characters')),
                ('next_speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_speaker', to='llm.characters')),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='llm.rooms')),
            ],
            options={
                'db_table': 'conversations',
                'indexes': [models.Index(fields=['room_id', 'created_at'], name='conversatio_room_id_090d1e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationHistories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='llm.rooms')),
            ],
            options={
                'db_table': 'conversation_histories',
                'indexes': [models.Index(fields=['room_id', 'created_at'], name='conversatio_room_id_81b107_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='characters',
            index=models.Index(fields=['room_id'], name='characters_room_id_903e89_idx'),
        ),
        migrations.AddIndex(
            model_name='shorttermmemories',
            index=models.Index(fields=['room_id', 'created_at'], name='short_term__room_id_daeb92_idx'),
        ),
        migrations.AddIndex(
            model_name='rooms',
            index=models.Index(fields=['created_at'], name='rooms_created_3ab07f_idx'),
        ),
    ]
