# Generated by Django 5.2.9 on 2025-12-19 06:49

import django.utils.timezone
import llm.models.db_models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAnalysisRecord',
            fields=[
                ('id', models.CharField(default=llm.models.db_models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('room_id', models.CharField(db_index=True, max_length=36)),
                ('character_id', models.CharField(db_index=True, max_length=36)),
                ('analysis_content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_analysis_records',
                'indexes': [models.Index(fields=['room_id', 'created_at'], name='admin_analy_room_id_a33749_idx'), models.Index(fields=['room_id', 'character_id'], name='admin_analy_room_id_2d226a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.CharField(default=llm.models.db_models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('room_id', models.CharField(db_index=True, max_length=36)),
                ('character_id', models.CharField(db_index=True, max_length=36)),
                ('character_name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('current_location', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conversation_histories',
                'indexes': [models.Index(fields=['room_id', 'created_at'], name='conversatio_room_id_81b107_idx'), models.Index(fields=['room_id', 'character_id'], name='conversatio_room_id_c8ad73_idx')],
            },
        ),
        migrations.CreateModel(
            name='LongTermMemory',
            fields=[
                ('id', models.CharField(default=llm.models.db_models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('room_id', models.CharField(db_index=True, max_length=36)),
                ('content', models.TextField()),
                ('embedding', models.BinaryField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'long_term_memories',
                'indexes': [models.Index(fields=['room_id'], name='long_term_m_room_id_e2a720_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShortTermMemory',
            fields=[
                ('id', models.CharField(default=llm.models.db_models.generate_uuid, max_length=36, primary_key=True, serialize=False)),
                ('room_id', models.CharField(db_index=True, max_length=36)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'short_term_memories',
                'indexes': [models.Index(fields=['room_id', 'created_at'], name='short_term__room_id_daeb92_idx')],
            },
        ),
    ]
